---
name: Docker Image CI

on:
  push:
    branches: [ main,oic ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY: ghcr.io
  REGISTRY_USER: ${{ github.actor }}
  REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build & deploy docker image
    steps:
      - uses: actions/checkout@v4
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PASSWORD }}

      - name: Set up environment variables
        run: |
          export CI_COMMIT_REF_SHORT=${GITHUB_REF##*/}
          export CI_COMMIT_REF_SLUG=${CI_COMMIT_REF_SHORT//./_}
          echo "CI_COMMIT_REF_SLUG=${CI_COMMIT_REF_SLUG}" >> $GITHUB_ENV
          export CI_PROJECT_NAME=${GITHUB_REPOSITORY##*/}
          echo "CI_PROJECT_NAME=${CI_PROJECT_NAME//_/-}" >> $GITHUB_ENV
          echo "CI_REGISTRY_IMAGE=${{ env.REGISTRY }}/${GITHUB_REPOSITORY}/oic:${CI_COMMIT_REF_SHORT}" >> $GITHUB_ENV
          echo "NODE_ENV=production" >> $GITHUB_ENV

      - name: Build image and publish to package repository
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ env.CI_REGISTRY_IMAGE }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          file: Dockerfile
